language: python
python:
- '2.7'
install:
- pip install six
- pip install python-coveralls
- pip install urllib3
- pip install requests
script: nosetests
after_success:
- coveralls
deploy:
  provider: pypi
  user: plasmashadow
  password:
    secure: DxS9FjGOtgtlrGKAGUHzWi485uYBILcYHjp3SIYDU7H9HOb9oVE1MrRijGI/JnAQPfS4Ksw2ILiZQfcErMhFMvgf6otRKmhdYq4VSgzAavAEBKpfU9gUhUx+SVWQ31bdSRz4QZmZ6xD1B2Qg0RbssqMGNpOssf62Wdj+GvX5ESy+xtD1QoSthh2LDx3VxGiKU6WCghY7HFpgUUMNDR6HzPz6peXhun5fR0xbjXH/Wo9XfkiRDrm8Osb9y+RdiRbifv4nkQ8k69/dG0vphatM1QEKuV6M/I8oMnNYcoEI/TY4iEzKszlmOPy9Kut6jYWJ0jTOrciYbK60DFxEJIH85L9w0fCmCnsJsF4ROs5cOximmHo5D02gJXA9krbAwnAV1JDRNu4SZ2BzA7dFhi/Kaa8E3Dtc5ELx88IP+fHg2GXQTlZHM/MyHvWlY9j4kPeAjqqaLYQp3Yl8BVKrbhgWTGy5KEW2sFxWy3Iz8umrr4XtL14u2Uls0+5HYmqDQLxNEetDOciKu29T3/g4Tr78KV16lk4Ken6Ooh0ro4B2C0BeVV9FY+HYTnjUBouhMF/qc0BIjW9BRPVLCz3li03X8UfTrvLWtUQsj8gBNKqEki1J8E74DXmcvg9YFienI5Zoq30r91icY8PSz4Vf/xREFyGx7zfm3ix6BLHAUb9IjbU=
  on:
    repo: plasmashadow/stackexchange
    branch: master
